### ISSUE TITLE
403 Error https://wabi-south-east-asia-redirect.analysis.windows.net/powerbi/metadata/models

### ISSUE THREAD

**Issue by sheldonyss** [Microsoft/powerbi-models#17]
I use Power BI Javascript sdk to integrate power bi report with my custom web application but I am always seeing this error in browser console window.

https://wabi-south-east-asia-redirect.analysis.windows.net/powerbi/metadata/models 403 forbidden.

However, my power bi report can be displayed correctly and I can load different report at run time using SDK and all filters seems working.

What is the cause of this error?

**Comment by ali-hamud** [comment]
It's a known bug. we will get to it :) you can still see your report, don't worry about it.

**Comment by ali-hamud** [comment]
This should be solved already. Please recheck

**Comment by sheldonyss** [comment]
This is not fixed. I am still seeing this error
![image](https://cloud.githubusercontent.com/assets/15058152/20297692/b9f840d2-ab4c-11e6-88c7-739973337e69.png)

**Comment by ali-hamud** [comment]
verified.
bug exists.

**Comment by joefreddy** [comment]
Is there any ETA or workaround for fixing this?
We need go live with our embedded app, but some of the visuals are not loading due to this issue.

**Comment by ali-hamud** [comment]
No. This must be something else. It should not affect visuals rendering.

**Comment by joefreddy** [comment]
This is what we get:
![image](https://cloud.githubusercontent.com/assets/15731122/20359097/a73bc882-ac2e-11e6-9010-83477fd82a8f.png)

**Comment by ali-hamud** [comment]
Can you give more context?
How you get your embed token?
Where does your report set?

**Comment by joefreddy** [comment]
Thanks, we get the token from app.powerbi.com (not embedded), basically the same way as in this sample:
https://github.com/Microsoft/PowerBI-CSharp/blob/master/samples/webforms/integrate-report-web-app/PBIWebApp/Default.aspx.cs

We tried both rendering the report with the basic js api (setting the token in the iframe message), like here:
https://github.com/Microsoft/PowerBI-CSharp/blob/master/samples/webforms/integrate-report-web-app/PBIWebApp/Default.aspx

and also tried it with the jquery api like here (we set the both the global token and in the embedconfig):
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embedding-Basics#powerbicom

**Comment by joefreddy** [comment]
Could it be related to this issue?
https://github.com/Microsoft/PowerBI-JavaScript/issues/76

**Comment by ali-hamud** [comment]
sure. it could be. I will ask about the state of the deployment.

**Comment by joefreddy** [comment]
Thanks

**Comment by ranbreuer** [comment]
Does this bug still exists?
We fixed this a while back

**Comment by MassTronic** [comment]
Hi ,i have this error my reports work but this error keeps showing POST https://wabi-us-north-central-b-redirect.analysis.windows.net/explore/explorations/551113/cache 401 (Unauthorized)    powerbiportal.dependencies.externals.bundle.min.js:114

**Comment by dead8171** [comment]
i am having this issue too I get this error when I try to load my report, it gives me this error

GET https://wabi-south-east-asia-redirect.analysis.windows.net/metadata/cluster 403 (Forbidden)

**Comment by loeds** [comment]
i had same problem too... my report didnt display

**Comment by ali-hamud** [comment]
There is a mix between two issues:
1) POST https://wabi-us-north-central-redirect.analysis.windows.net/explore/explorations/3985108/cache 401 (Unauthorized)
This issues is not solved yet, but it should not prevent the report from loading.

2) GET https://wabi-south-east-asia-redirect.analysis.windows.net/metadata/cluster 403 (Forbidden)
This issue is solved. if you have this issue, please make sure you pass a correct token type in embed settings. follow aka.ms/pbijs for examples of how to embed a report.

If you have more issues, please let me know.

**Comment by zebasyed** [comment]
Hi ,

Is the GET with 403 issue solved?As i am getting the same error 

Thanks in advance

**Comment by acomito** [comment]
same error here too

**Comment by puneet-openmed** [comment]
same here, the weird part is I have exact same cloned production code running without a glitch and dev keep generating this error.Don't know what is going on?

**Comment by Gulshan-S** [comment]
same error here too, the weird part is cloned Dev code is working fine in production branch, and Dev just producing this error.Need immediate fix
